[package]
name = "bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
#windows = "0.12.0"
windows = { git = "https://github.com/microsoft/windows-rs.git" }

[build-dependencies]
#windows = "0.12.0"
windows = { git = "https://github.com/microsoft/windows-rs.git" }
